config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, controllers: {
    sessions: 'admin_users/sessions'
  }, skip: %w[registrations]

  root to: 'application#redirect_to_sign_in'

  resources :admin_users, only: %w[#<WebFront:0x00007ffa4cf05750>]

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resource :user_bookings, only: :create
      resources :books, only: :index
    end
  end

  namespace :dashboard do
    # TODO: customizable table name
    devise_for :admin_users, controllers: {
      sessions: 'dashboard/admin_users/sessions',
      passwords: 'dashboard/admin_users/passwords'
    }, skip: %w[registrations]

    resources :admin_users, only: %w[index show]
  end

  get '*path' => redirect('/')

  unless Rails.env.development?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      admin_username = ENV['SIDEKIQ_DASHBOARD_USERNAME']
      admin_password = ENV['SIDEKIQ_DASHBOARD_PASSWORD']
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(admin_username)
      ) && ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(password),
        ::Digest::SHA256.hexdigest(admin_password)
      )
    end
  end
  mount Sidekiq::Web => '/sidekiq'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable,
         :trackable, :recoverable

  validates :email, presence: true
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :set_admin_user, only: %w[edit update destroy]

  def index
    @admin_users = AdminUser.order(created_at: :desc).page(params[:page])
  end

  private

  def set_admin_user
    @admin_user = AdminUser.find_by(id: params[:id])
  end

  def admin_user_params
    params.require(:admin_user).permit(
      :created_at, :updated_at, :email, :name, :password, :email
    )
  end
end

app/controllers/dashboard/admin_users/passwords_controller.rb
module Dashboard
  module AdminUsers
    class PasswordsController < Devise::PasswordsController
      layout 'dashboard_not_authenticated'

      def update
        self.resource = resource_class.reset_password_by_token(resource_params)
        yield resource if block_given?
        if resource.errors.empty?
          resource.unlock_access! if unlockable?(resource)
          if Devise.sign_in_after_reset_password
            flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
            set_flash_message!(:notice, flash_message)
            resource.after_database_authentication
            sign_in(resource_name, resource)
          else
            flash[:notice] = t('.success')
          end
          respond_with resource, location: after_resetting_user_password_path_for(resource)
        else
          set_minimum_password_length
          @error = resource.errors.full_messages.join(', ')
          respond_with resource
        end
      end

      private

      def after_resetting_admin_user_password_path_for(_)
        new_dashboard_admin_user_session_path
      end
    end
  end
end

app/controllers/dashboard/admin_users/sessions_controller.rb
module Dashboard
  module AdminUsers
    class SessionsController < Devise::SessionsController
      layout 'dashboard_not_authenticated'

      def after_sign_in_path_for(_)
        dashboard_admin_users_path
      end

      def after_sign_out_path_for(_)
        new_dashboard_admin_user_session_path
      end
    end
  end
end

app/controllers/dashboard/admin_users_controller.rb
module Dashboard
  class AdminUsersController < BaseController
    before_action :set_admin_user, only: %w[show edit update destroy]
    helper_method :order_params

    def index
      service = Search::AdminUsersService.new(params)
      @admin_users = service.execute
    end

    def show; end

    def order_params(order, direction)
      params.merge(o: order, d: direction, page: params[:page]).permit(:o, :d, :page)
    end

    private

    def set_admin_user
      @admin_user = AdminUser.find_by(id: params[:id])
    end

    def admin_user_params
      params.require(:admin_user).permit(
        :created_at, :updated_at, :email, :name, :password, :email
      )
    end
  end
end

app/controllers/dashboard/base_controller.rb
module Dashboard
  class BaseController < ApplicationController
    layout 'dashboard'
    before_action :authenticate_dashboard_admin_user!
  end
end

app/views/dashboard/admin_users/_breadcrumb.html.slim
.d-flex
  - data.each do |item|
    .ml-2.d-flex
      = link_to item[:text], item[:link]
      - if item != data.last
        .ml-2 >

app/views/dashboard/admin_users/index.html.slim
.main-content
  .container-fluid
    .header
      .header-body
        .row.align-items-end
          .col
            .header-pretitle
              h6 = t('.heading_sub')
            h1.header-title = AdminUser.model_name.human
          .col-auto
            = link_to t('.csv'), dashboard_admin_users_path(admin_user: @search_query, format: :csv), class: 'btn btn-info lift ml-3'


    .row.mt-4
      .col-12
        .card
          .table-responsive
            table.table.table-sm.card-table
              thead
                tr
                  th
                    .d-flex
                      .mr-2 = AdminUser.human_attribute_name(:id)
                      - if params[:d].present? && params[:d].include?('asc') && params[:o].include?('id')
                        = link_to '⋀', dashboard_admin_users_path(order_params('id', 'desc'))
                      - else
                        = link_to '⋁', dashboard_admin_users_path(order_params('id', 'asc'))
                  th
                    .d-flex
                      .mr-2 = AdminUser.human_attribute_name(:email)
                      - if params[:d].present? && params[:d].include?('asc') && params[:o].include?('id')
                        = link_to '⋀', dashboard_admin_users_path(order_params('id', 'desc'))
                      - else
                        = link_to '⋁', dashboard_admin_users_path(order_params('id', 'asc'))
                  th
                    .d-flex
                      .mr-2 = AdminUser.human_attribute_name(:created_at)
                      - if params[:d].present? && params[:d].include?('asc') && params[:o].include?('id')
                        = link_to '⋀', dashboard_admin_users_path(order_params('id', 'desc'))
                      - else
                        = link_to '⋁', dashboard_admin_users_path(order_params('id', 'asc'))
                  th
                    .d-flex
                      .mr-2 = AdminUser.human_attribute_name(:updated_at)
                      - if params[:d].present? && params[:d].include?('asc') && params[:o].include?('id')
                        = link_to '⋀', dashboard_admin_users_path(order_params('id', 'desc'))
                      - else
                        = link_to '⋁', dashboard_admin_users_path(order_params('id', 'asc'))
                  th
                    .d-flex
                      .mr-2 = AdminUser.human_attribute_name(:email)
                      - if params[:d].present? && params[:d].include?('asc') && params[:o].include?('id')
                        = link_to '⋀', dashboard_admin_users_path(order_params('id', 'desc'))
                      - else
                        = link_to '⋁', dashboard_admin_users_path(order_params('id', 'asc'))
                  th
                    .d-flex
                      .mr-2 = AdminUser.human_attribute_name(:name)
                      - if params[:d].present? && params[:d].include?('asc') && params[:o].include?('id')
                        = link_to '⋀', dashboard_admin_users_path(order_params('id', 'desc'))
                      - else
                        = link_to '⋁', dashboard_admin_users_path(order_params('id', 'asc'))
                  th
              tbody
                - @admin_users.each do |admin_user|
                  tr
                    td = admin_user.id
                    td = admin_user.email
                    td = admin_user.created_at
                    td = admin_user.updated_at
                    td = admin_user.email
                    td = admin_user.name
                    td = link_to t('.show'), dashboard_admin_user_path(admin_user), class: 'btn btn-primary btn-sm'

        = paginate @admin_users, views_prefix: 'dashboard'

app/views/dashboard/admin_users/show.html.slim
.main-content
  .container-fluid
    .header
      .header-body
        .row.d-flex.justify-content-between
          .col
            .header-pretitle
              h6 = t('.heading_sub')
            h1.header-title = AdminUser.model_name.human
          .mx-4.pt-2
            = render 'breadcrumb', data: [{ text: 'AdminUsers', link: '/dashboard/admin_users' }, { text: 'View AdminUser', link: "/dashboard/admin_users/#{@admin_user.id}" }]

    .row.justify-content-center
      .col-12.col-lg-10.col-xl-8
        .card
          .card-header
            h4.card-header-title = "#{AdminUser.model_name.human}詳細情報"
          .card-body
            .list-group.list-group-flush.my-n3

              .list-group-item
                .row.align-items-center
                  .col
                    .font-weight-base.mb-1 = AdminUser.human_attribute_name(:created_at)
                  .col-auto
                    = @admin_user.created_at
              .list-group-item
                .row.align-items-center
                  .col
                    .font-weight-base.mb-1 = AdminUser.human_attribute_name(:updated_at)
                  .col-auto
                    = @admin_user.updated_at
              .list-group-item
                .row.align-items-center
                  .col
                    .font-weight-base.mb-1 = AdminUser.human_attribute_name(:email)
                  .col-auto
                    = @admin_user.email
              .list-group-item
                .row.align-items-center
                  .col
                    .font-weight-base.mb-1 = AdminUser.human_attribute_name(:name)
                  .col-auto
                    = @admin_user.name